### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by atomic1fire** [Fmstrat/gam#1]
A license file with a source code license of your choice would probably help drive adoption of your project and would clear things up for contributors.

edit: I only bring this up because the copyright situation gets very murky when there's multiple contributors.

https://old.reddit.com/r/coolgithubprojects/comments/gvdl1d/github_application_manager_gam_its_like_aptyum/fsnzmxe/

**Comment by Fmstrat** [comment]
On it, will add a GPLv3 later this morning.

**Comment by Fmstrat** [comment]
https://github.com/Fmstrat/gam/commit/13d02d0405e2148a24d7261910b06af571c34d21
