### ISSUE TITLE
Without sudo?

### ISSUE THREAD

**Issue by dufferzafar** [Fmstrat/gam#2]
I was wondering if `sudo` is strictly required?

First, you'd have to read the config file from somewhere like $HOME/.gam.config or $HOME/config/gam.config

Then, in the config file, if I set the INSTALL_FOLDER to be a path under my $HOME directory, then things should work without `sudo`, right?

**Comment by Fmstrat** [comment]
I will look to add a `--user` flag for user mode, however it will not be able to install rpm or deb files.

**Comment by Fmstrat** [comment]
I will finish full testing on this later, but this seems to work well so far.

https://github.com/Fmstrat/gam/tree/usermode

**Comment by dufferzafar** [comment]
Okay, will test. 

What happens with GitHub projects that provide both tarballs and .deb files? Which of the files does it pick up?

**Comment by Fmstrat** [comment]
It will ask you to use the `--include/exclude` flag to select the right package in normal mode, in user mode deb and rpm will not even show up as valid releases.

**Comment by Fmstrat** [comment]
Tested and merged into master.
